### PR TITLE
Location generator

### PR DESCRIPTION
**Pull request by dvnstrcklnd**
- Added a CollectionLocationGenerator class
- Cleaned up and added some alphanumeric indexing methods in CollectionLocation

### CODE REVIEW

**Review by bjkeller — COMMENTED** [review]
So, there is nothing about collections in this code other than the name.  Also, the CDC layout is embedded in something that seems very general, but actually assumes a particular collection structure and is very specific.

I would strongly suggest rethinking this.

**Comment by dvnstrcklnd** [comment]
The CDC layout is really a placeholder. The plan is to get rid of it and replace it with something more general.

**Comment by dvnstrcklnd** [comment]
I could call it a PlateLayoutGenerator. Would that be OK?

**Comment by dvnstrcklnd** [comment]
I could create a class `MicrotiterPlate` to model these things, and it could have the Collection as an instance variable so that you don't have to interact with it directly. 

It would also have these methods that I added to CollectionLocation, which are really plate-oriented:
```ruby
  # Convert a letter to the corresponding array index
  #
  # @param letter [String] the letter (usually of a row)
  # @return Fixnum
  def letter_to_index(letter)
    alphabet_array.index(letter.upcase)
  end

  # Convert an array index to the corresponding letter of the alphabet
  #
  # @param index [Fixnum] the index (usually of a row)
  # @return String
  def index_to_letter(index)
    alphabet_array[index]
  end

  # Array of all letters of the alphablet in uppercase
  #
  # @return Array<String>
  def alphabet_array
    ('A'..'Z').to_a
  end

  # Get the alpha component of an alphanumumeric coordinate
  #
  # @param alphanum [String]
  # @return [String, nil] the first contiguous run of letters or nil if no
  #   letters are found
  def alpha_component(alphanum)
    mtch = alphanum.match(/[[:alpha:]]+/)
    return mtch[0] if mtch
  end

  # Get the numeric component of an alphanumumeric coordinate
  #
  # @param alphanum [String]
  # @return [Fixnum, nil] the first contiguous run of digits or nil if no
  #   digits are found
  def numeric_component(alphanum)
    mtch = alphanum.match(/\d+/)
    return mtch[0].to_i if mtch
  end
```

Conceptually, this would mimic the sample models that I started using last year.

**Comment by dvnstrcklnd** [comment]
I reverted the `CollectionLayoutGenerator` because it is bad and makes Ben grumpy. But the changes to `CollectionLocation` are good.

**Pull request merged**
