### PR TITLE
Updates to collection Display

### PR DESCRIPTION
**Pull request by malloc3**
This should display collection ID and better collection formatting

### CODE REVIEW

**Review by dvnstrcklnd — APPROVED** [review]
This looks good overall.

**Comment by dvnstrcklnd** [comment]
@malloc3 do these changes still need to be merged?

**Comment by dvnstrcklnd** [comment]
If so I would like to go through again and make sure that we aren't chaning files we don't intend to.

**Comment by malloc3** [comment]
Changes were have already been merged into master.  This PR should be closed and branch deleted @dvnstrcklnd

**Pull request closed without merging**
